# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetHubInfos <- function(m, tn_p, k) {
    .Call(`_MRHCA_GetHubInfos`, m, tn_p, k)
}

GetMrEm <- function(m, tn_p, k) {
    .Call(`_MRHCA_GetMrEm`, m, tn_p, k)
}

GetMrhcaFast <- function(m, mr_em, k, step_size = 50L) {
    .Call(`_MRHCA_GetMrhcaFast`, m, mr_em, k, step_size)
}

